### ISSUE TITLE
Fix readme

### ISSUE THREAD

**Issue by auroranockert** [audiocogs/flac.js#1]
There should be a proper README, which includes reference to libav and that it is available under LGPL, build instructions, usage, etc.

**Comment by devongovett** [comment]
So the decoder was directly ported from ffmpeg but the demuxer I wrote just from the spec... but it's probably fine to release the whole thing under the LGPL.  In cd19cd1f4ceaaa6f3375e9ef5a82c1cbd0506818 I added some file headers referencing these things, but they're different for both files because one was ported and one was not... Anyway, licensing is complicated stuff. Let me know what you think!

**Comment by auroranockert** [comment]
I think we should do everything under LGPL, the demux is useless without the decoder. If we want another license we can clean-room the decoder.

**Comment by devongovett** [comment]
LGPL is fine, and that is what I put on both. Not sure clean-rooming is worth the effort. :)

**Comment by auroranockert** [comment]
I am pretty convinced that it is not worth it.

**Comment by devongovett** [comment]
done.
