### ISSUE TITLE
Distortion in Firefox

### ISSUE THREAD

**Issue by arp242** [audiocogs/flac.js#19]
There seems to be quite a bit of distortion in Firefox, to the point where I consider this to be unusable. It's _mostly_ at the start in of the file, but also later on.

Chromium (39.0.2171.95) seems to work okay; I have this with my own testcode, and the demo app.

My code is simple:

```
        p = 'http://localhost/martin/new-audio/'
        player = AV.Player.fromURL(p + 'tone.flac')
        player.preload()
        setTimeout(function() { player.play() }, 3000)
```

I added the `preload` and `setTimeout` to make sure it's not because of a strange buffering issue ... I can verified that the file loads correctly in Firefox's network tab before it starts playing.

My testfile: http://tmp.arp242.net/tone.flac
I created this in Audacity (generate tone), and exported it to FLAC from there; It's not the only file that does this, I tried 3 other files (some FLAC files from my music collection) and they have the same problem...

I'm using Firefox 34.0.5 on Arch Linux (my system is updated). I don't have any other tabs open or the llke. I'm using aurora.js 0.4.4 and flac.js 0.2.1 (I downloaded the pre-builts).

**Comment by ghost** [comment]
Ampache utilizes this library for its web playback and has an issue with ajax-heavy UI operations. Perhaps this is the same bug?

https://github.com/audiocogs/aurora.js/issues/45

**Comment by arp242** [comment]
I'm just using a simple testpage (See above code). Nothing else going on...

**Comment by crackofdusk** [comment]
I have tried reproducing this with Firefox 35.0.1 on LInux. I have downloaded the pre-built files and used @Carpetsmoker's code.

I don't know what @Carpetsmoker calls distortion, but I can hear some pops at the beginning.

The file plays perfectly with the player on http://audiocogs.org/codecs/flac/. I last updated the files there on 1st June 2014, so that page definitely is a few aurora.js and flac.js versions behind.

The pops are also there if I load the flac file through the File API instead of HTTP.

I need to run more tests to pinpoint the version where the regression was introduced.

**Comment by arp242** [comment]
> I don't know what @Carpetsmoker calls distortion, but I can hear some pops at the beginning.

Yeah, that's what I meant.

Thanks for looking :-)

**Comment by ghost** [comment]
@crackofdusk, I'm curious that you have perfect playback on the test page because I have the same issue as in the bug report listed above on Win/Lin and Firefox/Chromium/Epiphany.

Perhaps these two bugs are related somehow.

**Comment by crackofdusk** [comment]
Note to self: here is the code I used to reproduce the issue: https://gist.github.com/crackofdusk/8199dd31f8bca54a105a
