### ISSUE TITLE
192kHz/24bit

### ISSUE THREAD

**Issue by auroranockert** [audiocogs/flac.js#7]
Apparently there is some bug in the 192kHz/24bit support, I didn't get more information than that. We should test it at some point.

**Comment by satazor** [comment]
There's a comment in the code saying that it requires 64 integer bits, which JS doesn't have. Is there any workaround for this?

**Comment by auroranockert** [comment]
You could implement 64-bit integers using double-double arithmetic, I think.

**Comment by mattberkowitz** [comment]
I saw a couple implementations when I briefly looked into this in conjunction with seek tables. http://docs.closure-library.googlecode.com/git/class_goog_math_Long.html seemed like a viable starting point (http://stackoverflow.com/questions/6041124/javascript-typed-arrays-64-bit-integers suggests there are no external dependencies)

**Comment by devongovett** [comment]
24-bit files are now fully supported as of 53e3f7c5387d1d2c672451d9b0af9e885a57366e along with the fixes described in #15.

I tried using google's Long library, but it was **way** too slow, causing files playing back to use over 80% CPU.  This is because it creates so many objects, rather than mutating the existing ones.  I pulled out some stuff we needed, and made some optimizations based on assumptions we can make that the general purpose math library cannot.  See comments in the code for details.

Performance isn't bad.  I'm seeing around 6-8% CPU usage on average for the 24-bit files I've tested (in the latest Chrome on Mac).  This isn't that much higher than 16-bit FLAC files on average, though the `multiply_add` function I added does show up first on a profile.  Anyway, this impact was to be expected, at least it works. :smile:

**Comment by Pheo-Player** [comment]
Just want to ask: Is the performance of 16bit files going to be affected by this update at all? Other than that, badass work.

**Comment by devongovett** [comment]
Nope, shouldn't be affected.  16-bit files use the exact same code as before.

**Comment by fabslab** [comment]
seems like the demo site is still running into this error, does it need updating? http://audiocogs.org/codecs/flac/

**Comment by philkunz** [comment]
any update here?
just tried the npm version on node and 16bit plays fine, but 24bit fails.

**Comment by devongovett** [comment]
npm version should work. what was the file you tried to play? not sure if the website got updated.

**Comment by philkunz** [comment]
about the testfiles:
24bit/96kHz encoded in flac, will retry with 192kHz, just saw the samplerate from all the files differ from 192kHz mentioned in the title...

@devongovett Do you have a Cloud9 account? If yes, mail me your username to office@philkunz.com, so I can give you access to a Cloud9 space that has the testfiles and a browserified test ready for you.
